name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: [Vault, PlaceholderAPI]
commands:
  balance:
    aliases: ["bal", "money"]
    description: Check your economy balance
  prismaeconomy:
    aliases: ["eco", economy]
    description: PrismaEconomy main command
  pay:
    description: "Give money to another player"